[MTB ]add kyverno policy - disallow-root-user
kubernetes-sigs/multi-tenancy pull request #1113
Opened 2020-09-17 02:59 UTC by realshuting

Fixes #1107.

/assign @JimBugwadia

2020-09-17 03:47 UTC, JimBugwadia commented
/ok-to-test

2020-09-17 03:54 UTC, JimBugwadia requested changes
@realshuting - can you also please update the list of tests here? 

https://github.com/kubernetes-sigs/multi-tenancy/tree/master/benchmarks#benchmarks

2020-09-28 04:24 UTC, JimBugwadia requested changes
can we remove pending from this and the require image pull policy?

2020-09-28 04:24 UTC, JimBugwadia commented on benchmarks/README.md
> +* [Require run as non-root user](kubectl-mtb/test/benchmarks/require_run_as_non_root_user) (**pending**)
can we remove **pending**?

2020-09-28 18:03 UTC, realshuting commented
/retest

2020-09-28 19:16 UTC, adrianludwin commented
/hold

2020-09-28 19:16 UTC, adrianludwin commented
Can you please remove all changes to HNC files from this PR?

2020-09-28 19:16 UTC, adrianludwin commented
This PR includes over 40 commits - is this what you intended?

2020-09-28 19:18 UTC, realshuting commented
> This PR includes over 40 commits - is this what you intended?

I didn't make any change to HNC, just rebased master branch.

2020-09-28 19:25 UTC, adrianludwin commented
I think something must have gone wrong in your rebase. If you look at this PR, you'll see that it includes 124 files, including incubator/hnc/Dockerfile and incubator/hnc/Makefile at a minimum.

Rebases are hard!

2020-09-28 19:31 UTC, realshuting commented
Usually I'm doing a merge instead of a rebase, that would bring an extra commit message though.

I'm not familiar with how "rebase" works here, what I can do is to close this PR and submit a new one on top of the current master. It's easier to track the changes that way.

/close

2020-09-28 19:31 UTC, closed without merging